---
title: "Getting Started OEIS.R"
author: "Enrique Pérez Herrero"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Introduction

# Installing and loading `OEIS.R` package 

## Installing package from Github

Github repository: https://github.com/EnriquePH/OEIS.R

```{r, eval=FALSE}
library(devtools)
devtools::install_github("EnriquePH/OEIS.R")
```

## Loading `OEIS.R` Package

```{r}
library(OEIS.R)
```

## Getting OEIS url

```{r}
OEIS_web_url()
OEIS_web_url(license = TRUE)
```

## Number of sequences in the encyclopedia

```{r}
OEIS_total_sequences()
```

# Loading a sequence

## S3 Class `OEIS_sequence`

```{r}
id <- "A001615"
A001615 <- OEIS_sequence(id)
class(A001615)
```

## Basic sequence information 

```{r}
A001615$ID
A001615$description
A001615$formerly
A001615$url
```

## Plotting the sequence

```{r}
plot(A001615)
```

```{r}
A001615$author
```


## Sequence's $Bib\TeX$ reference
```{r}
bref <- OEIS_bibtex(A001615)
print(bref, style = "Bibtex")
```

## Access $Bib\TeX$ fields

```{r}
bref$note
```

## Plotting with `ggplot2`

```{r}
library(ggplot2)
OEIS_ggplot(A001615) + 
  geom_line()
```


## Links

```{r}
library(knitr)

kable(data.frame(A001615$links))
```


